### ISSUE TITLE
Uncaught TypeError: Failed to set the 'textContent' property on 'Node'

### ISSUE THREAD

**Issue by pjeby** [crittermike/shortkeys#622] opened 2024-05-08 21:40 UTC
Since the latest update, I get this whenever I try to use a shortcut that runs a bookmarklet:

```
script-to-inject.js:1
Uncaught TypeError: Failed to set the 'textContent' property on 'Node': This document requires 'TrustedScript' assignment.
    at HTMLDocument.<anonymous> (script-to-inject.js:1:111)
```

**Comment by ryancu7** [comment] 2024-05-09 05:58
Me too

**Comment by pjeby** [comment] 2024-05-09 06:01
Also getting this for the same shortcut on a Windows 10 machine (prev. was Win 7):

```
content.js:1 Uncaught (in promise) Error: Extension context invalidated.
    at content.js:1:9901
    at new Promise (<anonymous>)
    at u (content.js:1:9827)
    at Object.apply (content.js:1:7297)
    at Object.doAction (content.js:1:16005)
    at content.js:1:16087
    at l (content.js:1:13923)
    at r._handleKey (content.js:1:15166)
    at h.handleKey (content.js:1:12062)
    at HTMLDocument.c (content.js:1:14174)
```

Both of these are for a bookmarklet I use in Gmail.

**Comment by piotr-dobrogost** [comment] 2024-05-09 12:16
Per comment https://github.com/crittermike/shortkeys/issues/621#issuecomment-2101710474 this issue is probably also a duplicate of #599.

**Comment by crittermike** [comment] 2024-08-18 15:55
Closing in favor of #599.

**Closed** 2024-09-09 20:33 UTC
