### ISSUE TITLE
'Run JavaScript' does not work on some sites

### ISSUE THREAD

**Issue by hababr** [crittermike/shortkeys#621] opened 2024-05-08 07:12 UTC
mail.google.com:
```
TypeError: Failed to set the 'textContent' property on 'Node': This document requires 'TrustedScript' assignment.
    at HTMLDocument.<anonymous> (script-to-inject.js:1:111)
```

linkedin.com:
```
Refused to execute inline script because it violates the following Content Security Policy directive:
```

**Comment by vtexperts** [comment] 2024-05-08 14:02
Same on mail.google.com
``Uncaught TypeError: Failed to set the 'textContent' property on 'Node': This document requires 'TrustedScript' assignment.
    at HTMLDocument.<anonymous> (script-to-inject.js:1:111)
```

**Comment by tjhorner** [comment] 2024-05-09 00:27
Duplicate of #599

**Comment by piotr-dobrogost** [comment] 2024-05-09 12:15
> Duplicate of #599

Too bad `TrustedScript` is not mentioned there.

**Comment by oniatsu** [comment] 2024-08-08 03:43
This symptom has not been resolved in the latest version of Shortkeys, 4.1.3.

Currently it also occurs on youtube.com.

(TrustedScript)[https://developer.mozilla.org/en-US/docs/Web/API/TrustedScript] and will not work without modifying the way the script is injected.



```
script-to-inject.js:1 
        
       Uncaught TypeError: Failed to set the 'textContent' property on 'Node': This document requires 'TrustedScript' assignment.
    at HTMLDocument.<anonymous> (script-to-inject.js:1:111)
```

```javascript
document.addEventListener("shortkeys_js_run", (function(e) {
    let t = document.createElement("script");
    t.textContent = e.detail,
    document.body.appendChild(t),
    document.body.removeChild(t)
}
));
```

**Comment by hababr** [comment] 2024-08-10 13:43
@oniatsu Works on the latest commit.

**Comment by oniatsu** [comment] 2024-08-10 14:08
@hababr Thank you! It certainly seemed to be fixed in the lastest commit.

---

However, I would install the latest version from the Chrome Web Store if possible.
I don't know why the latest version of the merged commit from a month ago is not up on the Chrome Web Store.

**Comment by crittermike** [comment] 2024-08-12 14:19
The Web Store hasn't been updated yet because the PR that fixed it (thanks to @tjhorner) mentioned

> Shortcuts with missing IDs will be added on next save. This means users will need to go to the config page at least once before their JS shortcuts will work.

I was hoping to fix that so that the upgrade itself would add missing IDs instead of forcing users to do a manual action, before updating the web store. I haven't been able to find time to mess with it, so if anyone wants to PR that, feel free! 

Also @hababr you mentioned this:

> @tjhorner Nice fix, thank you. After building a release for Chrome I had to fix service_worker.js, a function name was missing (registerHandlers).

Any chance you could PR that fix?

**Comment by hababr** [comment] 2024-08-14 18:14
@crittermike Will do.

**Comment by hababr** [comment] 2024-08-14 21:26
@crittermike Created - [PR](https://github.com/crittermike/shortkeys/pull/637)

**Comment by crittermike** [comment] 2024-08-21 16:07
Upcoming release is posted [here](https://github.com/crittermike/shortkeys/releases/tag/v4.1.4) for anyone who has capacity to test before I publish to the webstore.

**Closed by crittermike** 2024-08-21 16:07 UTC

**Comment by andrejguran** [comment] 2024-10-04 16:29
> Upcoming release is posted [here](https://github.com/crittermike/shortkeys/releases/tag/v4.1.4) for anyone who has capacity to test before I publish to the webstore.

I can confirm that it fixed the issue in chrome

**Comment by AlexByte** [comment] 2024-11-29 16:54
@crittermike When do you plan to publish it?

**Comment by crittermike** [comment] 2024-12-09 15:22
Oof, thanks for the nudge. Just submitted it for webstore review.
